In [ ]:
import pandas as pd
import numpy as np
import csv

In [ ]:
df = pd.read_csv('1000 most common words - Train.csv', header = None)
df.columns = ["Word"]
df = df["Word"].str.split(r'', expand=True)
df = df.replace('', 0)
df = df.fillna(value=0)
df.drop(df.columns[[0,17]],axis=1,inplace=True)

for i in range(1,17):
    if 0 in df[i]:
        continue
    else:
        df[i] = df[i].str.lower()
df.to_csv('Separated.csv',header=False,index=False)
df

     1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
0     c  e  n  t  e  r  0  0  0  0  0  0  0  0  0  0
1     g  e  s  c  h  i  c  k  l  i  c  h  k  e  i  t
2     s  u  0  0  0  0  0  0  0  0  0  0  0  0  0  0
3     p  i  s  t  a  0  0  0  0  0  0  0  0  0  0  0
4     p  e  r  h  a  p  s  0  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
3995  k  l  a  r  0  0  0  0  0  0  0  0  0  0  0  0
3996  h  a  d  0  0  0  0  0  0  0  0  0  0  0  0  0
3997  v  e  r  l  o  r  e  n  0  0  0  0  0  0  0  0
3998  s  u  b  s  t  a  n  c  e  0  0  0  0  0  0  0
3999  u  s  u  a  l  0  0  0  0  0  0  0  0  0  0  0

[4000 rows x 16 columns]